import type { FileNode, LiteLizardDocument } from '@litelizard/shared';
import type { DocumentStructureInput } from '../types/documentStructure.js';
export type EditorMode = 'writing' | 'structure' | 'reader';
export type ViewScale = 'micro' | 'macro';
interface AppState {
    rootPath: string | null;
    tree: FileNode[];
    currentFilePath: string | null;
    document: LiteLizardDocument | null;
    revision: number;
    dirty: boolean;
    apiKeyConfigured: boolean;
    editorMode: EditorMode;
    viewScale: ViewScale;
    analysisLayerOpen: boolean;
    statusMessage: string;
    openFolder: () => Promise<void>;
    createDocument: (title: string, parentPath?: string) => Promise<void>;
    createEntry: (parentPath: string, type: 'file' | 'folder', name: string) => Promise<void>;
    renameEntry: (targetPath: string, nextName: string) => Promise<void>;
    deleteEntry: (targetPath: string) => Promise<void>;
    loadDocument: (filePath: string) => Promise<void>;
    updateParagraph: (paragraphId: string, text: string) => void;
    reorderParagraphs: (orderedIds: string[]) => void;
    reorderChapters: (orderedIds: string[]) => void;
    replaceParagraphs: (paragraphTexts: string[]) => void;
    syncDocumentStructure: (input: DocumentStructureInput) => void;
    saveNow: () => Promise<void>;
    runAnalysis: () => Promise<void>;
    runAnalysisFor: (paragraphId: string) => Promise<void>;
    setEditorMode: (mode: EditorMode) => void;
    setViewScale: (viewScale: ViewScale) => void;
    toggleViewScale: () => void;
    cycleEditorMode: () => void;
    setAnalysisLayerOpen: (open: boolean) => void;
    toggleAnalysisLayer: () => void;
    bootstrapApiKeyStatus: () => Promise<void>;
    saveApiKey: (apiKey: string) => Promise<void>;
    clearApiKey: () => Promise<void>;
}
export declare const useAppStore: import("zustand").UseBoundStore<import("zustand").StoreApi<AppState>>;
export {};
